<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="es"> <!--<![endif]-->
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <!-- Place favicon.ico and apple-touch-icon.png in the root directory --> 
  <title>Sin Titulo</title>
  <?php //Tag::css('bienvenida') ?>
  <?php //Tag::css('style') ?>
  <?php Tag::css("main") ?>
  <?php Tag::css("normalize") ?>
  <?php Tag::css("bootstrap/css/bootstrap.min") ?>
  <?php echo Html::includeCss() ?>
  <?php echo Tag::js("vendor/modernizr-2.6.2.min") ?>
</head>
<body>
    <div id='content'>
    <header>
      <?php View::partial("menu_usuario") ?>
    </header>
        <?php View::content(); ?>  
    </div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.10.2.min.js"><\/script>')</script>
    <?php echo Tag::js("plugins") ?>
    <?php echo Tag::js("jquery/jquery.kumbiaphp") ?>
    <?php echo Tag::js("bootstrap/js/bootstrap.min") ?>
    <?php echo Tag::js("main") ?>
</body>
</html>
